---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: ruby
  commands:
    - gem install bundler
    - bundle
    - rspec
  environment:
    LANG: "C.UTF-8"
  when:
    branch:
    - master
    status:
    - success
- name: deploy
  image: docker/compose:1.27.4
  commands:
    - docker-compose build
    - docker-compose down
    - docker-compose up -d
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  depends_on:
    - build

trigger:
  branch:
  - master
