Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

AllCops:
  Exclude:
    - "spec/spec_helper.rb"
    - "Gemfile"
    - "Rakefile"

    